"""empty message

Revision ID: 0d770890a699
Revises: 62589fc504b2
Create Date: 2023-04-10 15:42:05.316508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d770890a699'
down_revision = '62589fc504b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_group_id_groups', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_group_id_groups', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
