"""changed group column to group_name

Revision ID: 62589fc504b2
Revises: 8ec4c5126555
Create Date: 2023-04-10 13:47:55.381769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62589fc504b2'
down_revision = '8ec4c5126555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(), nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
