"""reupdate

Revision ID: ee2c71552cb2
Revises: c4b83e7627f7
Create Date: 2023-04-06 15:49:54.507068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2c71552cb2'
down_revision = 'c4b83e7627f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('fill_color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('fill_color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
